appName: senior-peach-6
appUniqueId: faisal/senior-peach-6
appInfo:
  description: This is React Application
  appVersion: 1.0.4
  appRepoUrl: https://github.com/faisalarrowai/31.git
  appIconUrl: https://storage.googleapis.com/codeboltai.appspot.com/agents/8GXuJ6XQv4.png
  appAuthorUserId: faisal
  forkedFrom: codeboltadmin/basereactapp
technicalInfo:
  supportedLanguages:
    - typescript
  supportedFrameworks:
    - react
  secrets:
    - name: MONGO_URL
      description: MonogoDb URL
  services:
    - node:20+
    - python:2.13+
    - redis:any
  knowledgebases:
    - url:
        url: docs.test.com
        vectordbId: adsfasdfasd
        name: TestDocs
    - docs:
        url: asdfi/co/file
        vectordbId: asdfaga
        name: sampledoc
  instruction:
    - text: adsfadsfasdf
    - localfile:
        path: ./instruction.md
usage:
  develop:
    run:
      - shell:
          command: npm run dev
    agents:
      - codebolt_dev
    laynut: dev
  install:
    steps:
      - instruction:
          AIinstruction: Create this app
      - command:
          type: shell
          description: This installs the Npm
          command: npm install
    customInstallationAgent:
      enabled: true
      agent: codebolt_dev
  appUse:
    prerunsteps:
      - shell:
          command: npm run start
    agents:
      - codebol_sildes_generator
    layout: basic
    appPreview:
      type: web
